### ISSUE TITLE
README URLs need updating

### ISSUE THREAD

**Issue by ajnelson-nist** [casework/CASE-Implementation-Plaso#4]
The README still points to `casework`.

**Comment by vikhari** [comment]
Thanks for opening the issue. This was originally avoided because I thought the information was not ported yet. However, it seems identical to the ReadMe here: https://github.com/ucoProject/CASE

Link updated (1a5ab24) .

**Comment by ajnelson-nist** [comment]
Thanks!  But, I didn't notice the links (which needed fixing too), I noticed the README's `git clone` instructions.

**Comment by vikhari** [comment]
Ah, I see. That is now changed as well.
